### ISSUE TITLE
Fast tap on CollectionView prints a warnning on Android

### ISSUE THREAD

**Issue by ifurnadjiev** [eclipsesource/tabris-js#1404]
In the latest dev-app from Play Store (tabris.js 2.0-rc2 and above) relatively fast tap on CollectionView cell leads to the following warning in the console:
`Could not call method "insert" on tabris.CollectionView (Reason: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference)`

**Comment by ifurnadjiev** [comment]
Sometimes during the same fast tap operation the `select` event is fired with `index` `-1`. Is it possible the index property of the event to be -1?!

**Comment by ralfstx** [comment]
The problem appears to be a name clash between the recently added native `insert` method (2792ad555bfea362226388ff15976cffe35a9e41) and the native method of the same name in `CollectionView`.

**Comment by ralfstx** [comment]
The clash has been resolved. @ifurnadjiev Could you try again with the latest nightly?

**Comment by ifurnadjiev** [comment]
yes... the warning in the console is gone. Thanks... but I still get `event.index` -1 on fast tap in `select` event. But probably this is a completely different issue, which has to be addressed in the native code.

**Comment by ralfstx** [comment]
Thanks Ivan. Closing this issue as the warning is gone. The `-1` index should be tracked by another issue.
