### ISSUE TITLE
WebSocket .close() and .onclose() issues

### ISSUE THREAD

**Issue by Air16** [eclipsesource/tabris-js#1770]
### Problem description

Two issues with WebSocket :
1) Calling Websocket.close() triggers Websocket.onclose() but it does not close the connection on server side.
2) closing the connection on server side triggers Websocket.onclose() twice

### Expected behavior

1) should terminate the connection immediately on server side
2) should trigger onclose() event only once

### Environment

- Tabris.js version: latest (built with "latest" on 29th nov 2018)
- Device: Lenovo Tablet
- OS: Android 7.0

### Code snippet

```javascript
function test(){
    let socket = new WebSocket('ws://192.168.1.15:8890', 'raw-protocol'); 
    
    socket.onopen = (event) => {
      console.info('ws.onopen');
    };
    
    socket.onmessage = (event) => {
      console.info("ws.onmessage : " + event.data);
      if (event.data.trim() == 'q')
        socket.close();
    };
    
    socket.onerror = (event) => {
      console.info("ws.onerror");	
    };

    socket.onclose = (event) => {
      console.warn("ws.onclose");	
    };
}
```
Together with a nodejs websocket server (same as chat server example) and another ws client connected to the same server.

Both tests work OK from within a web page or a nodejs script.

Issue 1 : 
1) call test()
=> console = "ws.onopen"
2) from another websocket client, send "q"
=> console = "ws.onmessage : q" + "ws.onclose"
=> connection is closed on server side. THIS does not occur with Tabris

Issue 2 :
1) call test()
=> console = "ws.onopen"
2) close clients on server side
=> normal console = "ws.onclose".
=> Tabris console = "ws.onclose" + "ws.onclose" (the event is triggered twice)
![image](https://user-images.githubusercontent.com/45421540/49340229-64d63d00-f63d-11e8-990c-026833e059b6.png)

**Comment by mpost** [comment]
Thanks for opening the issue. We will look into it asap.

**Comment by mpost** [comment]
@Air16 We have fixed the the close issues you have described in the latest nightly builds. To try it out please build against `nightly` (3.x) or `nightly-2.x` (2.x) in your package.json. 

Closing this issue for now. Please reopen of the problems have not been resolved.

**Comment by Air16** [comment]
Just built the example with 2.x nightly. No change at all, both bugs are still there with the exact same test code given above.

**Comment by Air16** [comment]
it's ok it works.
