### ISSUE TITLE
Stop sending listen for 'dispose' on Composite

### ISSUE THREAD

**Issue by jordiboehmelopez** [eclipsesource/tabris-js#349]
Tabris.js should not send a listen operation for 'dispose' on Composite to the client, as this does not exist.

**Comment by ralfstx** [comment]
Are you saying that the JS sends a `notify` operation to the client? Or do you mean `listen`?

**Comment by jordiboehmelopez** [comment]
Sorry. Right. `listen` - I corrected the title and description.

**Comment by ralfstx** [comment]
@tbuschto Shouldn't this been fixed with 6dc5d9a?

**Comment by ralfstx** [comment]
@jordiboehmelopez could you verify that you still receive the listen operations? This should have been fixed in 0.9.3 already.

**Comment by ralfstx** [comment]
I've verified once again that there is no listen operation sent for Composites. This issue is stale.
